language: node_js

cache: yarn

node_js:
  - 8
  - 10
  - 11
  - 12

script:
  - yarn test:prod
  - yarn build

jobs:
  include:
    - stage: coverage
      node_js:
        - 10
      script:
        - yarn test:prod && yarn report-coverage
    - stage: deploy
      node_js:
        - 10
      script:
        - yarn build
    #     - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy-docs; fi
    #     - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn semantic-release; fi

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
